// This file is auto-generated by scripts/sync-tokens.mjs
// Do not edit this file directly.
export default {
  "colors": {
    "light": {
      "primary": {
        "100": "#bfe3e8",
        "200": "#8cd9e3",
        "300": "#5ccfde",
        "400": "#29bdd4",
        "500": "#08a6bf",
        "600": "#058fa6",
        "700": "#005461",
        "800": "#053b42",
        "900": "#0a262b"
      },
      "gray": {
        "100": "#e6edf5",
        "200": "#c9d6e0",
        "300": "#bdccd9",
        "400": "#a8bacc",
        "500": "#8a9eb3",
        "600": "#6b7d8f",
        "700": "#59697a",
        "800": "#424d59",
        "900": "#2e363b",
        "000": "#ffffff"
      }
    },
    "dark": {
      "primary": {
        "100": "#0a262b",
        "200": "#053b42",
        "300": "#005461",
        "400": "#058fa6",
        "500": "#08a6bf",
        "600": "#29bdd4",
        "700": "#5ccfde",
        "800": "#8cd9e3",
        "900": "#bfe3e8"
      },
      "gray": {
        "100": "#262629",
        "200": "#33363b",
        "300": "#3d4247",
        "400": "#4d5257",
        "500": "#5c636e",
        "600": "#787d87",
        "700": "#8c94a1",
        "800": "#adb8c4",
        "900": "#e8e8e8",
        "000": "#17171c"
      }
    },
    "green": {
      "100": "#8afcbd",
      "200": "#45e88c",
      "300": "#29e67d",
      "400": "#12db6b",
      "500": "#03c759",
      "600": "#03b552",
      "700": "#059c47",
      "800": "#007d38",
      "900": "#035224"
    },
    "blue": {
      "100": "#cfe3ff",
      "200": "#9ec4ff",
      "300": "#6ea8ff",
      "400": "#3d8cfc",
      "500": "#0d6efc",
      "600": "#0a59c9",
      "700": "#084299",
      "800": "#052b66",
      "900": "#031733"
    },
    "indigo": {
      "100": "#e0cffc",
      "200": "#c29efa",
      "300": "#a370f7",
      "400": "#8540f5",
      "500": "#660ff2",
      "600": "#520dc2",
      "700": "#3d0a91",
      "800": "#290561",
      "900": "#140330"
    },
    "red": {
      "100": "#ffe3e6",
      "200": "#f2adb5",
      "300": "#eb878f",
      "400": "#e35c6b",
      "500": "#db3645",
      "600": "#b02938",
      "700": "#852129",
      "800": "#59141c",
      "900": "#2b0a0d"
    },
    "bg": {
      "primary": {
        "level1": "#08a6bf",
        "level1-hover": "#058fa6"
      },
      "neutral": {
        "level1": "#e6edf5",
        "level1-hover": "#c9d6e0",
        "level2": "#a8bacc",
        "surface": "#ffffff",
        "surface-hover": "#e6edf5",
        "base": "#ffffff",
        "base-hover": "#e6edf5",
        "disabled-checked": "#bdccd9"
      },
      "status": {
        "negative": "#db3645",
        "positive": "#03c759",
        "information": "#0d6efc"
      }
    },
    "border": {
      "primary": {
        "level1": "#08a6bf"
      },
      "neutral": {
        "level1": "#c9d6e0",
        "level1-hover": "#a8bacc",
        "level2": "#a8bacc",
        "disabled": "#c9d6e0",
        "active": "#2e363b"
      },
      "status": {
        "negative": "#db3645",
        "positive": "#03c759",
        "information": "#0d6efc"
      }
    },
    "icon": {
      "primary": {
        "level1": "#08a6bf"
      },
      "neutral": {
        "level1": "#2e363b",
        "level2": "#59697a",
        "white": "#ffffff",
        "inverse": "#ffffff",
        "disabled": "#a8bacc"
      },
      "status": {
        "negative": "#db3645",
        "positive": "#03c759",
        "information": "#0d6efc"
      }
    },
    "text": {
      "primary": {
        "base": "#08a6bf"
      },
      "neutral": {
        "base": "#2e363b",
        "description": "#59697a",
        "disabled": "#a8bacc",
        "inverse": "#ffffff",
        "white": "#ffffff"
      },
      "status": {
        "negative": "#db3645",
        "positive": "#03c759",
        "information": "#0d6efc"
      }
    },
    "btn": {
      "bg": {
        "primary": {
          "base": "#08a6bf",
          "hover": "#058fa6"
        },
        "normal": {
          "base": "#ffffff",
          "hover": "#e6edf5"
        },
        "error": {
          "base": "#db3645",
          "hover": "#db3645"
        }
      },
      "border": {
        "primary": "#08a6bf",
        "normal": "#a8bacc"
      },
      "text": {
        "primary": "#08a6bf",
        "normal": "#2e363b",
        "disabled": "#a8bacc",
        "error": "#db3645",
        "inverse": "#ffffff",
        "white": "#ffffff"
      }
    },
    "input": {
      "bg": {
        "base": "#ffffff",
        "disabled": "#e6edf5"
      },
      "border": {
        "base": "#c9d6e0",
        "hover": "#a8bacc",
        "active": "#2e363b",
        "error": "#db3645"
      },
      "text": {
        "normal": "#2e363b",
        "disabled": "#a8bacc",
        "error": "#db3645"
      },
      "icon": {
        "normal": "#2e363b",
        "disabled": "#a8bacc"
      }
    },
    "control": {
      "bg": {
        "primary": "#08a6bf",
        "normal": "#ffffff",
        "disabled": "#e6edf5",
        "disabled-checked": "#bdccd9"
      },
      "border": {
        "primary": "#08a6bf",
        "level1": "#c9d6e0",
        "level1-hover": "#a8bacc",
        "disabled": "#c9d6e0"
      },
      "text": {
        "normal": "#2e363b",
        "disabled": "#a8bacc"
      },
      "icon": {
        "primary": "#08a6bf",
        "normal": "#2e363b",
        "white": "#ffffff",
        "inverse": "#ffffff",
        "disabled": "#a8bacc"
      }
    },
    "toggle": {
      "bg": {
        "primary": "#08a6bf",
        "normal": "#e6edf5",
        "disabled": "#a8bacc",
        "disabled-checked": "#bdccd9"
      },
      "text": {
        "normal": "#2e363b",
        "disabled": "#a8bacc"
      },
      "icon": {
        "inverse": "#ffffff",
        "white": "#ffffff"
      }
    }
  },
  "spacing": {
    "heading-small": "16px",
    "heading-medium": "18px",
    "heading-large": "20px",
    "heading-xlarge": "24px",
    "body-small": "13px",
    "body-medium": "14px",
    "body-large": "16px"
  },
  "borderRadius": {
    "mini": "2px",
    "small": "4px",
    "medium": "6px",
    "large": "8px",
    "xlarge": "12px",
    "xxlarge": "16px",
    "full": "40px"
  }
};
